service: demo-service

provider:
  name: aws
  # runtime: python3.7

# you can overwrite defaults here
#  stage: dev
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*" 

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    runtime: python3.7
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "question_id" : "$input.params("question_id")" }'
  hello-go:
    runtime: go1.x
    handler: bin/main
    events:
      - http:
          path: /
          method: get
          integration: lambda


resources:
  Resources:
    DemoDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: question_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: question_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: question_table

